# Generated by Django 2.1.5 on 2019-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=100)),
                ('_class', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('qq', models.CharField(max_length=20)),
                ('wechat', models.CharField(max_length=20)),
            ],
        ),
    ]
