# Generated by Django 3.0.1 on 2021-06-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='hightlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='relevantMedicine',
            field=models.ManyToManyField(to='wall.Medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='toxicity',
            field=models.CharField(choices=[('无毒', '无毒'), ('小毒', '小毒'), ('有毒', '有毒'), ('大毒', '大毒')], default='无毒', max_length=10),
        ),
    ]
