# Generated by Django 3.1.6 on 2021-02-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='love',
            new_name='lovee',
        ),
    ]
