# Generated by Django 3.0.1 on 2021-06-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20210621_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='hightlight',
            new_name='highlight',
        ),
    ]
