# Generated by Django 3.1.6 on 2021-02-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20210207_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='lovee',
            new_name='love',
        ),
    ]
