# Generated by Django 2.1.5 on 2019-05-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20190523_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/avatar/default.png', upload_to='img/avatar'),
        ),
    ]
