# Generated by Django 3.1.6 on 2021-02-07 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20210207_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love',
            name='thumbsUpUser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='love',
            name='userTo',
            field=models.ManyToManyField(related_name='userTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
