# Generated by Django 3.1.6 on 2021-02-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_auto_20210207_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='love',
            new_name='lovee',
        ),
    ]
