# Generated by Django 2.1.5 on 2019-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_comment_image_love'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='love',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='wall.Comment'),
        ),
        migrations.AlterField(
            model_name='love',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='wall.Image'),
        ),
    ]
