# Generated by Django 3.0.1 on 2021-06-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_auto_20210621_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='composition',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ManyToManyField(blank=True, to='wall.Medicine'),
        ),
    ]
