# Generated by Django 3.1.6 on 2021-02-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_auto_20210207_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='lovee',
            new_name='love',
        ),
    ]
