# Generated by Django 3.0.1 on 2021-06-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_auto_20210628_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='_type',
            field=models.CharField(choices=[('解表剂', '解表剂'), ('泻下剂', '泻下剂'), ('和解剂', '和解剂'), ('清热剂', '清热剂'), ('祛暑剂', '祛暑剂'), ('温里剂', '温里剂'), ('表里双解剂', '表里双解剂'), ('补益剂', '补益剂'), ('固涩剂', '固涩剂'), ('安神剂', '安神剂'), ('开窍剂', '开窍剂'), ('理气剂', '理气剂'), ('理血剂', '理血剂'), ('治风剂', '治风剂'), ('治燥剂', '治燥剂'), ('祛湿剂', '祛湿剂'), ('祛痰剂', '祛痰剂'), ('消食剂', '消食剂'), ('驱虫剂', '驱虫剂'), ('涌吐剂', '涌吐剂'), ('治痈殇剂', '治痈殇剂')], max_length=50),
        ),
    ]
