# Generated by Django 2.1.5 on 2019-05-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_auto_20190524_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='love',
            name='isAnony',
            field=models.BooleanField(default=False),
        ),
    ]
