# Generated by Django 3.1.6 on 2021-02-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_auto_20210207_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='love',
            name='isTop',
            field=models.BooleanField(default=False),
        ),
    ]
