# Generated by Django 3.1.6 on 2021-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_love_istop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hot',
            name='publisher',
        ),
        migrations.AddField(
            model_name='hot',
            name='tags',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
