# Generated by Django 2.1.5 on 2019-05-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_love_isanony'),
    ]

    operations = [
        migrations.AddField(
            model_name='love',
            name='thumbsUp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
