# Generated by Django 3.0.1 on 2021-07-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_user_recite_everydayamount_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recite_bank_medicine',
            field=models.ManyToManyField(blank=True, related_name='recite_bank_medicine', to='wall.Medicine'),
        ),
    ]
