# Generated by Django 3.0.1 on 2021-07-01 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_user_recite_bank_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recite_bank_medicine',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recite_everydayAmount_medicine',
        ),
        migrations.CreateModel(
            name='Medicine_Recite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('everydayAmount', models.IntegerField(default=0)),
                ('todayFinishedAmount', models.IntegerField(default=0)),
                ('medicine', models.ManyToManyField(blank=True, to='wall.Medicine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
