# Generated by Django 3.1.6 on 2021-02-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_auto_20210209_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hot',
            name='tags',
        ),
        migrations.AddField(
            model_name='hot',
            name='_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
