# Generated by Django 2.1.5 on 2019-05-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_love_thumbsup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='love',
            name='thumbsUp',
        ),
        migrations.AddField(
            model_name='love',
            name='thumbsUpUser',
            field=models.ManyToManyField(blank=True, to='wall.User'),
        ),
    ]
