# Generated by Django 3.1.6 on 2021-02-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0009_auto_20210209_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
