# Generated by Django 2.1.5 on 2019-05-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0009_auto_20190525_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='love',
            name='nameTo',
            field=models.CharField(default='TA', max_length=20),
        ),
    ]
