# Generated by Django 3.0.1 on 2021-07-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0009_auto_20210701_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine_recite',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicine_recite',
            name='todayFinishedAmount',
        ),
        migrations.AddField(
            model_name='medicine_recite',
            name='allReviewMedicine',
            field=models.ManyToManyField(blank=True, related_name='allReviewedMedicine', to='wall.Medicine'),
        ),
        migrations.AddField(
            model_name='medicine_recite',
            name='allUnrecitedMedicine',
            field=models.ManyToManyField(blank=True, related_name='allUnrecitedMedicine', to='wall.Medicine'),
        ),
        migrations.AddField(
            model_name='medicine_recite',
            name='chapters',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine_recite',
            name='lastReciteDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicine_recite',
            name='todayReviewMedicine',
            field=models.ManyToManyField(blank=True, related_name='todayReviewMedicine', to='wall.Medicine'),
        ),
        migrations.AddField(
            model_name='medicine_recite',
            name='todayUnrecitedMedicine',
            field=models.ManyToManyField(blank=True, related_name='todayUnrecitedMedicine', to='wall.Medicine'),
        ),
        migrations.AddField(
            model_name='medicine_recite',
            name='todayWillReciteAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine_recite',
            name='totalAmount',
            field=models.IntegerField(default=0),
        ),
    ]
