# Generated by Django 3.0.1 on 2021-07-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0010_auto_20210701_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_recite',
            name='todayWillReviewAmount',
            field=models.IntegerField(default=0),
        ),
    ]
