# Generated by Django 2.1.5 on 2019-05-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0010_love_nameto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-id',)},
        ),
    ]
