# Generated by Django 3.1.6 on 2021-02-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0010_auto_20210210_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot',
            name='_type',
            field=models.CharField(choices=[('新闻', '新闻'), ('通知', '通知'), ('招标公告', '招标公告'), ('中标公告', '中标公告'), ('瓜', '瓜')], default='新闻', max_length=20),
        ),
    ]
