# Generated by Django 2.1.5 on 2019-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0011_auto_20190526_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='user_comments', to='wall.Comment'),
        ),
    ]
