# Generated by Django 3.1.6 on 2021-02-10 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0012_lecture_lecturerinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ('-startDate',)},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='date',
        ),
        migrations.AddField(
            model_name='lecture',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
