# Generated by Django 3.0.1 on 2021-07-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0012_medicine_recite_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField()),
                ('linkUrl', models.URLField(blank=True)),
            ],
        ),
    ]
