# Generated by Django 3.0.1 on 2021-07-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0013_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='linkUrl',
            field=models.URLField(null=True),
        ),
    ]
