# Generated by Django 3.0.1 on 2021-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0014_auto_20210703_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='linkUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
