# Generated by Django 3.1.6 on 2021-02-11 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0014_auto_20210210_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lose',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='lose',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='lose',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wall.lose'),
            preserve_default=False,
        ),
    ]
