# Generated by Django 3.1.6 on 2021-02-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0015_auto_20210211_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='img/wall'),
            preserve_default=False,
        ),
    ]
