# Generated by Django 3.0.1 on 2021-07-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0015_auto_20210703_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_recite',
            name='isRandom',
            field=models.BooleanField(default=True),
        ),
    ]
