# Generated by Django 2.1.5 on 2019-05-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0015_auto_20190530_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='lose',
            name='comments',
            field=models.ManyToManyField(blank=True, to='wall.Comment'),
        ),
    ]
