# Generated by Django 3.1.6 on 2021-02-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0016_auto_20210211_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='lose',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wall.lose'),
            preserve_default=False,
        ),
    ]
