# Generated by Django 3.0.1 on 2021-07-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0016_medicine_recite_israndom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_recite',
            name='lastReciteDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
