# Generated by Django 2.1.5 on 2019-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0017_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('A', models.CharField(max_length=50)),
                ('B', models.CharField(max_length=50)),
                ('C', models.CharField(max_length=50)),
                ('D', models.CharField(max_length=50)),
                ('isMultiple', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=10)),
            ],
        ),
    ]
