# Generated by Django 3.0.1 on 2021-07-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0018_auto_20210721_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='_type',
            field=models.CharField(choices=[('解表药', '解表药'), ('清热药', '清热药'), ('泻下药', '泻下药'), ('祛风湿药', '祛风湿药'), ('化湿药', '化湿药'), ('利水渗湿药', '利水渗湿药'), ('温里药', '温里药'), ('理气药', '理气药'), ('消食药', '消食药'), ('驱虫药', '驱虫药'), ('止血药', '止血药'), ('活血化瘀药', '活血化瘀药'), ('化痰止咳平喘药', '化痰止咳平喘药'), ('安神药', '安神药'), ('平肝息风药', '平肝息风药'), ('开窍药', '开窍药'), ('补虚药', '补虚药'), ('收涩药', '收涩药'), ('涌吐药', '涌吐药'), ('涌吐药', '涌吐药'), ('攻毒杀虫止痒药', '攻毒杀虫止痒药'), ('拨毒化腐生肌药', '拨毒化腐生肌药'), ('/', '/')], max_length=20),
        ),
    ]
