# Generated by Django 2.1.5 on 2019-06-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0018_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='isMultiple',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bank',
            name='questionType',
            field=models.CharField(choices=[('singleA', '单选-题型A'), ('singleB', '单选-题型B'), ('mutiple', '多选'), ('blank', '填空'), ('judge', '判断'), ('qa', '问答')], default='singleA', max_length=10),
        ),
    ]
