# Generated by Django 3.1.6 on 2021-02-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0019_auto_20210213_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='lose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.lose'),
        ),
        migrations.AlterField(
            model_name='image',
            name='love',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.love'),
        ),
    ]
