# Generated by Django 2.1.5 on 2019-06-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0020_auto_20190602_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='E',
            field=models.CharField(default='', max_length=50),
        ),
    ]
