# Generated by Django 2.1.5 on 2019-06-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0021_bank_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='E',
            field=models.CharField(max_length=50),
        ),
    ]
