# Generated by Django 2.1.5 on 2019-06-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0022_auto_20190603_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='A',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='B',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='C',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='D',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='E',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
