# Generated by Django 3.1.6 on 2021-02-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0022_auto_20210213_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='image',
            name='love',
        ),
        migrations.AddField(
            model_name='image',
            name='loses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.lose'),
        ),
        migrations.AddField(
            model_name='image',
            name='loves',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.love'),
        ),
    ]
