# Generated by Django 2.1.5 on 2019-06-03 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0023_auto_20190603_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='love',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='questionType',
            field=models.CharField(choices=[('singleA', '单选-题型A'), ('singleB', '单选-题型B'), ('multiple', '多选'), ('blank', '填空'), ('judge', '判断'), ('qa', '问答')], default='singleA', max_length=10),
        ),
        migrations.AlterField(
            model_name='lose',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
