# Generated by Django 3.1.6 on 2021-02-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0024_auto_20210213_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='images',
        ),
        migrations.AddField(
            model_name='comment',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.deal'),
        ),
        migrations.AddField(
            model_name='image',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.deal'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='lose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.lose'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='love',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.love'),
        ),
    ]
