# Generated by Django 3.1.6 on 2021-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0025_auto_20210213_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='new',
            field=models.FloatField(),
        ),
    ]
