# Generated by Django 2.1.5 on 2019-06-08 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0026_auto_20190608_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='publicDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
