# Generated by Django 3.1.6 on 2021-02-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0026_auto_20210213_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='_help',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.help'),
        ),
    ]
