# Generated by Django 2.1.5 on 2019-06-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0027_auto_20190608_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, to='wall.Comment'),
        ),
    ]
