# Generated by Django 3.1.6 on 2021-02-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0028_auto_20210214_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
    ]
