# Generated by Django 2.1.5 on 2019-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0028_article_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='love',
            name='userTo',
        ),
        migrations.AddField(
            model_name='love',
            name='userTo',
            field=models.ManyToManyField(blank=True, related_name='user_to', to='wall.User'),
        ),
    ]
