# Generated by Django 3.1.6 on 2021-02-16 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0029_remove_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='_from',
            field=models.CharField(choices=[('love', 'love'), ('lose', 'lose'), ('deal', 'deal'), ('help', 'help'), ('article', 'article')], max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='_type',
            field=models.CharField(choices=[('thumbsUp', 'thumbsUp'), ('comment', 'comment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='errorBook',
            field=models.ManyToManyField(null=True, related_name='errorBook', to='wall.Bank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='messages',
            field=models.ManyToManyField(null=True, related_name='messages', to='wall.Message'),
        ),
    ]
