# Generated by Django 3.1.6 on 2021-02-16 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0030_auto_20210216_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='errorBook',
            field=models.ManyToManyField(related_name='errorBook', to='wall.Bank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='wall.Message'),
        ),
    ]
