# Generated by Django 2.1.5 on 2019-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0030_article_thumbsupuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default='', max_length=50),
        ),
    ]
