# Generated by Django 3.1.6 on 2021-02-18 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0031_auto_20210216_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acupoint',
            name='channel',
            field=models.CharField(choices=[('手太阴肺经', '手太阴肺经'), ('手阳明大肠经', '手阳明大肠经'), ('足阳明胃经', '足阳明胃经'), ('足太阴脾经', '足太阴脾经'), ('手少阴心经', '手少阴心经'), ('手太阳小肠经', '手太阳小肠经'), ('足太阳膀胱经', '足太阳膀胱经'), ('足少阴肾经', '足少阴肾经'), ('手厥阴心包经', '手厥阴心包经'), ('手少阳三焦经', '手少阳三焦经'), ('足少阳胆经', '足少阳胆经'), ('足厥阴肝经', '足厥阴肝经'), ('任脉', '任脉'), ('督脉', '督脉')], max_length=50),
        ),
        migrations.AlterField(
            model_name='love',
            name='thumbsUpUser',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='errorBook',
            field=models.ManyToManyField(blank=True, related_name='errorBook', to='wall.Bank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='messages', to='wall.Message'),
        ),
        migrations.DeleteModel(
            name='AcupointChannel',
        ),
    ]
