# Generated by Django 2.1.5 on 2019-06-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0031_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('cover', models.ImageField(default='img/club/default.png', upload_to='img/club')),
                ('president', models.CharField(max_length=20)),
                ('vicePresident', models.CharField(max_length=20)),
                ('presidentAssistant', models.CharField(max_length=20)),
                ('planDirector', models.CharField(max_length=20)),
                ('financeDirector', models.CharField(max_length=20)),
                ('feedbackDirector', models.CharField(max_length=20)),
                ('ITDirector', models.CharField(max_length=20)),
                ('propagandaDirector', models.CharField(max_length=20)),
                ('otherDirectors', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
