# Generated by Django 2.1.5 on 2019-09-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0032_auto_20190629_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='cover',
        ),
        migrations.AlterField(
            model_name='club',
            name='ITDirector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ITDirector', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='club',
            name='feedbackDirector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackDirector', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='club',
            name='financeDirector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeDirector', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='club',
            name='otherDirectors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherDirectors', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='club',
            name='planDirector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planDirector', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='club',
            name='presidentAssistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidentAssistant', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='club',
            name='propagandaDirector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagandaDirector', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='club',
            name='vicePresident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vicePresident', to='wall.User'),
        ),
    ]
