# Generated by Django 3.1.6 on 2021-02-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0032_auto_20210218_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='application',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='function',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='song',
            field=models.CharField(max_length=100),
        ),
    ]
