# Generated by Django 2.1.5 on 2019-09-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0034_auto_20190920_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hot',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
