# Generated by Django 2.1.5 on 2019-09-20 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0035_auto_20190920_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='learningDirector',
            field=models.ManyToManyField(blank=True, related_name='learningDirector', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbsUpUser',
            field=models.ManyToManyField(blank=True, related_name='thumbsUp', to='wall.User'),
        ),
        migrations.RemoveField(
            model_name='club',
            name='ITDirector',
        ),
        migrations.AddField(
            model_name='club',
            name='ITDirector',
            field=models.ManyToManyField(blank=True, related_name='ITDirector', to='wall.User'),
        ),
        migrations.RemoveField(
            model_name='club',
            name='feedbackDirector',
        ),
        migrations.AddField(
            model_name='club',
            name='feedbackDirector',
            field=models.ManyToManyField(blank=True, related_name='feedbackDirector', to='wall.User'),
        ),
        migrations.RemoveField(
            model_name='club',
            name='financeDirector',
        ),
        migrations.AddField(
            model_name='club',
            name='financeDirector',
            field=models.ManyToManyField(blank=True, related_name='financeDirector', to='wall.User'),
        ),
        migrations.RemoveField(
            model_name='club',
            name='planDirector',
        ),
        migrations.AddField(
            model_name='club',
            name='planDirector',
            field=models.ManyToManyField(blank=True, related_name='planDirector', to='wall.User'),
        ),
        migrations.RemoveField(
            model_name='club',
            name='propagandaDirector',
        ),
        migrations.AddField(
            model_name='club',
            name='propagandaDirector',
            field=models.ManyToManyField(blank=True, related_name='propagandaDirector', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='love',
            name='userFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='wall.Comment'),
        ),
    ]
