# Generated by Django 3.1.6 on 2021-02-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0035_commonfile_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonfile',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.match'),
        ),
    ]
