# Generated by Django 2.1.5 on 2019-09-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0036_auto_20190920_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love',
            name='userFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFrom', to='wall.User'),
        ),
        migrations.AlterField(
            model_name='love',
            name='userTo',
            field=models.ManyToManyField(blank=True, related_name='userTo', to='wall.User'),
        ),
    ]
