# Generated by Django 3.1.6 on 2021-02-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0036_commonfile_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
