# Generated by Django 3.1.6 on 2021-02-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0037_auto_20210223_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='prizeDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='requirement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='totalBonus',
            field=models.IntegerField(default=0),
        ),
    ]
