# Generated by Django 2.1.5 on 2019-09-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0037_auto_20190920_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('lecturer', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=10)),
            ],
        ),
    ]
