# Generated by Django 2.1.5 on 2019-09-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0040_auto_20190922_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
