# Generated by Django 2.1.5 on 2019-09-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0041_message_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='messages', to='wall.Message'),
        ),
    ]
