# Generated by Django 2.1.5 on 2019-10-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0043_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='男', max_length=5),
        ),
    ]
