# Generated by Django 3.0.1 on 2019-12-31 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0045_user_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.Bank_Subject')),
            ],
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.Bank_Chapter'),
        ),
    ]
