# Generated by Django 3.0.1 on 2019-12-31 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0046_auto_20191231_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_subject',
            name='subjectType',
            field=models.CharField(choices=[('zy', '中医'), ('xy', '西医')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
