# Generated by Django 3.0.1 on 2020-01-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0048_auto_20191231_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='isBlankSeq',
            field=models.BooleanField(default=True),
        ),
    ]
