# Generated by Django 3.0.1 on 2020-01-04 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0049_bank_isblankseq'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('allQuestions', models.IntegerField()),
                ('correctQuestions', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.User')),
            ],
        ),
    ]
