# Generated by Django 3.0.1 on 2020-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0051_auto_20200104_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankstatistics',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='user',
            name='errorBook',
            field=models.ManyToManyField(blank=True, related_name='errorBook', to='wall.Bank'),
        ),
    ]
