# Generated by Django 2.1.5 on 2020-01-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0053_auto_20200108_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='following', to='wall.User'),
        ),
    ]
