# Generated by Django 2.1.5 on 2020-01-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0054_user_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lose',
            name='loseDate',
            field=models.DateTimeField(),
        ),
    ]
