# Generated by Django 3.0.1 on 2020-04-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0054_user_followings'),
        ('wall', '0055_article_isadopted'),
    ]

    operations = [
    ]
