# Generated by Django 2.1.5 on 2020-05-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0055_auto_20200114_1207'),
        ('wall', '0056_merge_20200411_2145'),
    ]

    operations = [
    ]
