# Generated by Django 2.1.5 on 2020-07-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0057_merge_20200518_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_JinGui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.User')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='bank',
            name='questionType',
            field=models.CharField(choices=[('singleA', '单选-题型A'), ('singleB', '单选-题型B'), ('multiple', '多选'), ('blank', '填空'), ('judge', '判断'), ('term', '名词解释'), ('qa', '问答'), ('case', '病案分析')], default='singleA', max_length=10),
        ),
        migrations.AlterField(
            model_name='bank',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lose',
            name='loseDate',
            field=models.CharField(max_length=20),
        ),
    ]
