# Generated by Django 2.1.5 on 2020-07-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0059_activity_jingui_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_jingui',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
