# Generated by Django 2.1.5 on 2020-07-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0060_auto_20200724_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_jingui',
            name='audio',
            field=models.FileField(default='audio/JinGui/default.mp3', upload_to='audio/JinGui'),
        ),
        migrations.AlterField(
            model_name='activity_jingui',
            name='content',
            field=models.TextField(default='元气满满的一天～'),
        ),
    ]
